exports.arr=[
    {name:"Gta V",
    img:"https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png",
    desc:"sdksdskmk"},
    {name:"Red Dead Redemption 2",
    img:"https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg",
    desc:"sdksdskmk"},
    {name:"Call of Duty: Black Ops 4",
    img:"https://upload.wikimedia.org/wikipedia/en/1/1c/Call_of_Duty_Black_Ops_4_official_box_art.jpg",
    desc:"sdksdskmk"},
    {name:"Call of Duty: Black Ops Cold War",
    img:"https://upload.wikimedia.org/wikipedia/en/3/31/BOCW_Cover_Art.jpg",
    desc:"sdksdskmk"},
    {name:"Call of Duty: Black Ops 6",
    img:"https://upload.wikimedia.org/wikipedia/en/c/c9/Call_of_Duty_Black_Ops_6_Key_Art.png",
    desc:"sdksdskmk"},
    {name:"Call of Duty: Infinite Warfare",
    img:"https://upload.wikimedia.org/wikipedia/en/8/87/Call_of_Duty_Infinite_Warfare_cover.jpg",
    desc:"sdksdskmk"},
    {name:"Grand Theft Auto VI",
    img:"https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Grand_Theft_Auto_VI.png/220px-Grand_Theft_Auto_VI.png",
    desc:"sdksdskmk"},
    {name:"Max Payne 3",
    img:"https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Max_Payne_3_Cover.jpg/220px-Max_Payne_3_Cover.jpg",
    desc:"Max Payne 3 is a 2012 third-person shooter game developed and published by Rockstar Games. The game was first released for PlayStation 3 and Xbox 360 on May 15, 2012; a Windows port was released on May 29, followed by an OS X port on June 20, 2013.[3] It is the sequel to Max Payne 2: The Fall of Max Payne and is the third entry in the Max Payne series. It is also backwards compatible on Xbox One and Xbox Series X/S.[4]"},
    {name:"Mafia III",
    img:"https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Mafia_III_cover_art.jpg/220px-Mafia_III_cover_art.jpg",
    desc:"Mafia III is a 2016 action-adventure video game developed by Hangar 13 and published by 2K. It was released in October 2016 for PlayStation 4, Windows, and Xbox One, in May 2017 for macOS,[2] and in October 2021 for Google Stadia. It is the sequel to Mafia II and the third installment in the Mafia series. Set within the fictional city of New Bordeaux (based on New Orleans) in 1968, the story follows former criminal and Vietnam veteran Lincoln Clay, who is forced to return to a life of crime to help his adoptive family settle problems with the local branch of the Mafia. After the Mafia betray and murder his family, Lincoln embarks on a quest for revenge while slowly building a criminal empire and seizing power from other criminal organisations in the city"},
]